### ISSUE TITLE
File upload support?

### ISSUE THREAD

**Issue by RichBurdes** [guillaumemeyer/YammerTabForTeams#1]
Hey Guillaume,
Does the tab support uploads like in the main Yammer UI - so the little paper clip in the text entry box to add images into Yammer etc?
Thanks and great work!

**Comment by guillaumemeyer** [comment]
As it uses the standard Yammer embed component, the file / picture upload behaviour should work properly.
Just keep in mind that as it's embedded in the Teams browser in Tab, some security issues may appear in some circumstances.

**Comment by guillaumemeyer** [comment]
Works perfectly on our environments.
