### ISSUE TITLE
Cann't set Yammer feed.

### ISSUE THREAD

**Issue by frpatsan37** [guillaumemeyer/YammerTabForTeams#2]
In the feed id Window the fields don't appear so can't connect to Yammer. how to correct this?
Thank you.
Patrick

**Comment by guillaumemeyer** [comment]
Hi, MSFT is doing a lot of changes to Teams clients before reaching the GA...
I'll investigate those issues asap after GA announcement.

**Comment by guillaumemeyer** [comment]
Hi, the tab is now back online !
